SHOW WAREHOUSES;

CREATE WAREHOUSE demo_warehouse
WITH
WAREHOUSE_SIZE = "X-Small"
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = "For demo purposes";

SHOW WAREHOUSES;

ALTER WAREHOUSE demo_warehouse
SET MAX_CLUSTER_COUNT = 3;

SHOW WAREHOUSES;